#define DEVICE_ID "DEVICE_ID"
#define WIFI_SSID "Unknown"
#define WIFI_PASS "aabbccdd"
#define MQTT_BROKER "puffin.rmq2.cloudamqp.com"
#define MQTT_PORT 1883
#define MQTT_USERNAME "gwbvwhzr:gwbvwhzr"
#define MQTT_PASS "BH4UyDm74GHbzdsYJOFtvZL7LTIM_bNB"
#define MQTT_SUBSCRIBE_QOS 2
#define MQTT_MESSAGE_QOS 2
#define MQTT_MESSAGE_RETAINED false
#define TOPIC "main/update"
