on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Node MCU Build & Deploy
    steps:
      - name: Check out repo
        uses: actions/checkout@v2.5.0
      - name: Compile .ino
        uses: ArminJo/arduino-test-compile@v3
        with:
          sketch-names: Sketch.ino
          sketch-names-find-start: Sketch/
          required-libraries: PubSubClient
          arduino-board-fqbn: esp8266:esp8266:nodemcuv2
          platform-default-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
          set-build-path: true
      - name: Create HTTP tunnel
        id: http-tunnel
        uses: luisboto/ngrok-tunnel-action@v0.1.7.2
        with:
          timeout: 5m
          port: 3000
          ngrok_authtoken: 2KmgTSe0szH8BLV7IUz0sirHZYc_AkYkmGuF3UPeU4MNsgHE
          tunnel_type: http
          save_url_to_filename: ${{ github.workspace }}/tunnelURL.md
      - name: Deploy
        id: deployment
        uses: potaesm/github-actions-arduino@v1.3.3
        with:
          deviceId: DEVICE_ID
          binaryBuildPath: ${{ github.workspace }}/Sketch/build/
          mqttUrl: mqtt://puffin.rmq2.cloudamqp.com
          mqttUsername: gwbvwhzr:gwbvwhzr
          mqttPassword: BH4UyDm74GHbzdsYJOFtvZL7LTIM_bNB
          mqttTopic: main/update
          tunnelUrlFilePath: ${{ github.workspace }}/tunnelURL.md
          fileServerPort: 3000
          timeLimit: 300000
      - name: Get Result
        run: echo "The deployment was ${{ steps.deployment.outputs.result }}"